name: Docker Build Image
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - tools/**

# Allow only one Docker build image build to run at a time for the entire smithy-rs repo
concurrency:
  group: ci-docker-build-yml
  cancel-in-progress: true

env:
  ecr_repository: public.ecr.aws/w0m4q9l7/github-awslabs-smithy-rs-ci

jobs:
  rebuild-docker-build-image:
    runs-on: ubuntu-latest
    name: Rebuild image
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: |
        IMAGE_TAG="$(git rev-parse HEAD)"
        cd tools/ci-build
        docker build -t "${{ env.ecr_repository }}:${IMAGE_TAG}" --file base-image.dockerfile .
    - name: Acquire credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.SMITHY_RS_PUBLIC_ECR_PUSH_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: us-west-2
    - name: Upload image
      run: |
        IMAGE_TAG="$(git rev-parse HEAD)"
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        docker push "${{ env.ecr_repository }}:${IMAGE_TAG}"
